name: Everlive sockets CI CD

on: 
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate release
        uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'

      - run: mix deps.get --only prod
      - run: PORT=${{ secrets.PORT }} SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} MIX_ENV=prod mix release

      - name: Copy build folder via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          password: ${{ secrets.SCP_PASSWORD }}
          port: ${{ secrets.SCP_PORT }}
          source: "_build/prod"
          target: "/var/www/develop/live.e-ver/back"
          strip_components: 2
